### ISSUE TITLE
Lỗi trong script cài đặt keystone

### ISSUE THREAD

**Issue by ducnc** [vietstacker/openstack-juno-multinode-U14.04-v1#1]
Hi các anh. 
Trong file control-4.keystone.sh, file cấu hình keystone.conf khai báo:

``` sh
[database]
connection = mysql://keystone:$KEYSTONE_PASS@$CON_MGNT_IP/keystone
```

Biến $KEYSTONE_PASS có lẽ phải khai báo là $KEYSTONE_DBPASS. Do các mật khẩu đều giống nhau nên khi cài không sing ra lỗi. Nếu cấu hình mật khẩu khác nhau sẽ có lỗi khi thực thi shell này.
:)

**Comment by congto** [comment]
Oke ! Anh sẽ fix lại để đúng với mọi trường hợp !
